name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: public
